### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by smcbrien** [rhel-labs/learn-katacoda#101]
### Step 1:

"In this lab you will have access to the following hosts:"  The rest of that first sentence is just fluff language (which if translated is just more stuff to translate without providing any actionable content).

You might consider using a graphic instead of a table, though the tradeoff is while it would look better, now you have to generate graphics if you make a change to the names/IPs in your table...

cat /etc/redhat-release  It's clickable, why obscure the actual filename with a glob?  (unless you're also wanting them to be able to execute these steps on a cent or oracle box...)

I'd add the output you expect them to see, like:
<pre class="file">
Red Hat Enterprise Linux release 8.1 (Ootpa)
</pre>

From the above, you can see that this system is running Red Hat Enterprise Linux (RHEL) 8 update release 1.

Under Examining /etc/hosts section, "we are using DNS to resolve hostnames."  I would describe this as more 'host mapping in /etc/hosts'.  While /etc/hosts is the first place checked by the local resolver, it's not "DNS" per se.  Later, I would change the term "DNS name" to "hostname"

Like the /etc/redhat-release output, you can show the output of /etc/hosts and make any observations or callouts from that after you show the output.

In the instructions you talk about ssh'ing to the hosts, but you never provide username/password.  Also, I would go ahead and add a tab for each of the hosts to the lab environment (which would be auto-logged in as root).  Also, here I wouldn't make them clickable since the result would be to have the displayed terminal [control node] then ssh'ed into host02 and then host02's shell ssh'ed into host03.

### Step 2

Second paragraph, since you already used 'code' highlighting in the previous sentence, I'd do it again here.  If you don't want to do that, the file should be referred to with it's name (non-capitalized A).  Though this might have been a mis-header tagging since after the filename it looks like another sentence is starting.

I would suggest changing the "documentation" link to something more specific like "Ansible Configuration Settings" documentation.  Though it looks like the link 

"configured in the home directory on the control node"; who's home directory?

I would show some output of the 'cat ansible.cfg', not the whole thing, you can use << OUTPUT ABRIDGED >> inside the <pre> tags to show just what you are interested in.  But that way, your follow-up about the inventory or stdout_callback parameters has context [and their default values are shown]

I think you need some more detail on the two things you're calling out. inventory might be a straightforward file location or something easy to grock. stdout_callback is there a reason you chose to switch it from JSON to YAML?

It looks like the 'documentation' link goes to the same place as above.  Again, I would recommend the title of the document being linked rather than 'documentation'.  I think the link worked better above because the content you were referring to was on the page when they opened the page.  Here, I think you need to use a bit more context/expectation setting like: "A full list of all Ansible configuration settings is available on the 'Ansible Configuration Settings' documentation, also linked above.  The settings are listed alphabetically later in the page, after the initial file location documentation."

### Step 3

Looks like your header isn't tagged as a header at the top of the page.

Who's home directory does this reside in?  Might be worthwhile to change the command to 'cat ~/hosts' or 'cat /root/hosts' so that there's not confusion with /etc/hosts talked about just two steps before.

"There is an implicit group named [all]."  I would use something like 'automatically created group' or 'default group' instead of using implicit.

There's a lot of looking on this page, with very little action.  That may be because you don't want them actually editing things because, vi is hard.  Katacoda has an editor they use, I wonder if that would provide an easier interface so they could actually do something like populate the password field or add a host to [web] group definition?

### Step 4
I would show the output of ansible --version in a <pre> block, then talk to that block of output later.

'which inventory we are parsing' change parsing to 'using' or a more simple word that means the same thing.

The above seems out of place on this step.  Shouldn't it go in the previous step to allow them to 'validate' the environment?  That would make this page all about the commands and modules.

I'd show the output of the different --list-hosts commands then they can see for themselves on the instructions (potentially in addition to the terminal window) the differences you're talking about in the text.

Same with the ping module, show them the output so that when you talk about 'hostname and SUCCESS' they can look at the output provided or, the advanced user, would compare your provided output to the output on their screen as well.

**Comment by IPvSean** [comment]
@smcbrien appreciate it!  Most of the feedback makes sense and I was on the fence with some things.  I think your comments got formatted oddly in this issue, there is like double scrolls bars for me?
![image](https://user-images.githubusercontent.com/6537680/77599969-e14cf900-6edc-11ea-9af8-9c6500282146.png)

anyways only a few things didn't make sense to me where I need more clarification-> 

**Step 1:**
>cat /etc/redhat-release It's clickable, why obscure the actual filename with a glob? (unless you're also wanting them to be able to execute these steps on a cent or oracle box...)

I think I might have already fixed this before you commented.  It now reads-> 

A control node is any machine with Ansible installed. All three nodes are running Red Hat Enterprise Linux 8. To see what version of Red Hat Enterprise is running on the server use the Linux `cat` command to examine the `/etc/redhat-release` file.    

`cat /etc/redhat-release`{{execute}}


> In the instructions you talk about ssh'ing to the hosts, but you never provide username/password.

So I did.... but then I found out that it just works without it... I don't quite understand the environment.  There is no ~/.ssh/config file but if you just ssh host2 or ssh host3 it will just login as root.

>Also, I would go ahead and add a tab for each of the hosts to the lab environment (which would be auto-logged in as root). 

Do you have an example of that you could link me?  I can try that.  The other problem is that you can't actually verify the hostname has changed if you are already logged into via this interface.  The hostname never changes, which is the goal of the playbook.  So then I feel like it is more awkward to ssh to yourself... but I am not sure.  If the student exits it logs out of the terminal permanently.

---

**Step 3**
>Looks like your header isn't tagged as a header at the top of the page.

What does this mean?  Maybe I fixed it already?

>There's a lot of looking on this page, with very little action.  That may be because you don't want them actually editing things because, vi is hard.  Katacoda has an editor they use, I wonder if that would provide an easier interface so they could actually do something like populate the password field or add a host to [web] group definition?

originally this was on purpose b/c ansible was taking so long to install... I think I am going to move that  to the foreground and change it around slightly because I agree.  Although for this exercise and the next one I don't actually want them editing Ansible Playbooks.  I want to have 2-3 read-only exercises because YAML is very difficult for novices and I want to give them some quick wins.
